name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test
